apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  echoedDictionary: 
{{ toYaml .Values.TestDictionary | indent 4 }}
  newDictionary:
    {{ .Values.TestKey}}: {{ .Values.TestValue}}

  lookupValue: {{ get .Values.TestDictionary .Values.TestKey }}
  keyPresent: {{ hasKey .Values.TestDictionary .Values.TestKey }}
  updatedDict:
{{ $updatedDict := deepCopy .Values.TestDictionary }}
{{ $_ := set $updatedDict .Values.TestKey .Values.TestValue }}
{{ toYaml $updatedDict | indent 4 }}

  removedDict:
{{ $updatedDict := deepCopy .Values.TestDictionary }}
{{ $_ := unset $updatedDict .Values.TestKey }}
{{ toYaml $updatedDict | indent 4 }}

  omittedDict:
{{ omit .Values.TestDictionary .Values.TestKey | toYaml | indent 4 }}

  dictionaryKeys:
{{ keys .Values.EmptyDictionary | sortAlpha | toYaml | indent 4 }}

  dictionaryValues:
{{ values .Values.EmptyDictionary | sortAlpha | toYaml | indent 4 }}
